env:
  global:
  - secure: qmIqMAH9Cke/j9WsdTUIh/BM/XG0tk2BhbU80V6JPh+o03yRJm2+c+DS89x/RZ1VfigvnepBSIA4Zn+qaC1fCKjtW4Yg9MiOG9d2ghI8rzxAyUdjoM/YZl448FJtFZE/7DQ+qnod8LfWx63F5kVVe0UjwrrbEHJMaJ7h6V8BgRKvyz02P/ZACuhP+OwZ9rXNI9oC9j92LEI22L/SlPxWMtzqdlosOZrk0q+6Vq07iHkkRvIp4Ynj1udBf5fK6OOKOIOnn5LJqh/i7dXmlZ+GGpNsKLUmaeEPXkGd8XylXIeU8DERI13zAkUK6UQGwGFIsOqnMrGoulNZI4xW3X47vo5CbPe9RTpyEeFGqxRTXf67UgZdD46SCv8cDK3LcYfAMmy6FQLk44tgnHFrDXcp+AIN0OR6+ffQJxd3Geqx7lBLRH15uFn29l29hNmmJSZri/qa//l1soRJa1GbRYQMWgb4sckQBxNVGAvJT53farhF1zrx3lmBmyWXdbWlj/Vnctg6MtytLVxkreqbi5Cs30CrsOedoynwClJevJorCEk7st1m8D6xMJNk6B8kt8yPBr3o5xwLBJKtyon9W4SihCUYoGjfnnNCzrJLVQMvi081nQoJmaklxG9HUkutFV/68Kna3VXECx12Fm83UIHHptEdP4r+1WRnFkVpOO+RKPg=
  - secure: NxcKwqoF5PHk6pKRlBdVoaGq6RfV3HGAqsGprCVgnTJwiCs7Oqk9m0glbxi+xScw32M0cya3VBdft7NpmTO/uG7YhFKffKLxb/2kTEepRW8Dz8r9wgVL2WbwoXCnc9ysvYkMp0pKrN9hTC8RPc+z4xOVqZzSYQ/mEf5HX1il8MdOtBAYFod9r+rQzC4goRYjSDAM13KYUFFSIFHV51dEd9dEQbeocTWYhg+WugIfrYW3EvdqLsRhVl2W9WyIWwKzeypQlajD7F5NfdBdevdsFv2Xr3ZCgVYYxmHJTbY3YpAbwSaTUAmDQM0giQYn2ZDDS9JIeb71fZPVWHbhJ7pvZhjS0bLV27/v/+MnJBOsVXcR8mHLRNJDlT5sxOad4mFqkdzWmCCkKiM42+c82xI4DzDrkunk5wk1SwUkKpLe+8HIDjCnVR9wvd3biFDBjx+eswoqPuPPyhcARLHhbhWvRZS9bH8i6PIFK+hGiHXGAR6+n5WsDD3wmhIDwAq46qpXnczigGNCh4+r4AbIe8ZcTzeSi+t2QBd4Ob4Fy7HB5Lt3toXke0Jtq6FHABGQWWzP5Hm/uKPgU4gzH8h2igQ8NwJVGtNQ08Uoa+tAqx24ly3za3o4WAhj5pIoprMwOFbq46ogqwHoeYEm/nQCyLXIwA0SezNEVfKHYet9BNPat14=
  - DEPLOYMENT_DIR=deployment
  - TERRAFORM_DIR=/opt/terraform
  - AWS_DEFAULT_REGION=eu-central-1

notifications:
  email: false
git:
  depth: 5
  quiet: true

jobs:
  include:
    - stage: "Infra"
      name: "deploy infrastructure"
      language: bash
      before_script: cd $DEPLOYMENT_DIR
      before_install:
        - wget -q https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
        - unzip terraform_0.11.11_linux_amd64.zip -d $TERRAFORM_DIR
        - test "$TRAVIS_BRANCH" = "master" && export ENV="prod" || export ENV="dev"
      script: $TERRAFORM_DIR/terraform init && $TERRAFORM_DIR/terraform plan && $TERRAFORM_DIR/terraform apply -auto-approve -var env=$ENV

    - stage: "Tests"
      name: "unit tests"
      language: python
      python:
        - "3.6"
      install: pip install -r requirements_test.txt
      script: python -m unittest discover

    - stage: "Deploy"
      name: name: "deploy chalice app"
      language: python
      python:
        - "3.6"
      script: ./deploy_app_and_ui.sh
